apiVersion: app.kubebuilder.io/v1
kind: DeployObject
metadata:
  name: falcon
spec:
  image: nginx:1.19.6-alpine
  replicas: 2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010
